<?php

/**
 * @file
 * Content for page with portal subdomain list
 */
function portal_subdomain_page() {

   menu_tree_set_path('microgame_portal', 'portal/admin');
  
  // get all themes
  $all_themes = list_themes();
  $theme_list = array();
  foreach ($all_themes as $theme_name => $theme)
  {
      $theme_list[$theme_name] = $theme->info['name'];
  }
  
  $header = array(
      array('data' => t('ID'), 'field' => 'sdid', 'sort' => 'desc'),
      array('data' => t('Name'), 'field' => 'name'),
      array('data' => t('Group name'), 'field' => 'group_name'),
      array('data' => t('Theme'), 'field' => 'theme_name'),
      array('data' => t('Created by'), 'field' => 'created_by_name'),
      array('data' => t('Updated by'), 'field' => 'updated_by_name'),
      array('data' => t('Created on'), 'field' => 'created_on'),
      array('data' => t('Updated on'), 'field' => 'updated_on'),
  );

  $query = db_select('microgame_subdomains', 'm');
    $query->join('users', 'u', 'm.created_by_uid = u.uid');
    $query->join('users', 'v', 'm.updated_by_uid = v.uid');
    $query->fields('m');
    $query->addField('u', 'name', 'created_by_name');
    $query->addField('v', 'name', 'updated_by_name');
    $details = $query->extend('PagerDefault')->limit(10)->extend('TableSort')->orderByHeader($header)->execute()->fetchAssoc();
  
//  /$query = db_select('microgame_subdomains', 'm')->fields('m')->extend('PagerDefault')->limit(10)->extend('TableSort')->orderByHeader($header);
  $result = $query->execute()->fetchallAssoc('sdid');

  $rows = array();
  foreach ($result as $row) {
    $fields = array();
    foreach ($header as $col) {
      if ($col['field'] == 'created_on' || $col['field'] == 'updated_on') {
        $fields[$col['field']] = format_date($row->$col['field'], 'short');
      } 
      else if ($col['field'] == 'theme_name') {
        $fields[$col['field']] = $theme_list[$row->$col['field']];
      }
      else {
        $fields[$col['field']] = $row->$col['field'];
      }
    }
    $fields['edit'] =  l(t('edit'),  'portal/admin/subdomains/edit/' .  $row->name);
    $fields['games'] =  l(t('games'),  "portal/admin/subdomains/{$row->name}/games/");
    $rows[] = $fields;
  }

  /*
    $table['header'] = $header;
    $table['attributes'] = array('class' => array('mg_table', 'subdomain_table'));
    $table['caption'] = '';
    $table['colgroups'] = array();
    $table['sticky'] = "";
    $table['empty'] = t('No subdomains have been configured');
    $table['rows'] = $rows;
    return theme_table($table);
   */

  $link = l(t('Create a new subdomain'),  'portal/admin/subdomains/create');
  
  $output = array(
      'first_para' => array(
          '#type' => 'markup',
          '#markup' => "<p>{$link}</p>",
      ),
      'second_para' => array(
          '#theme' => 'table',
          '#header' => $header,
          '#attributes' => array('class' => array('mg_table', 'subdomain_table')),
          '#empty' => t('No subdomains have been configured'),
          '#rows' => $rows,
      ),
  );
  return $output;

}

?>
